### ISSUE TITLE
Make sponsorship proposal to BAML

### ISSUE THREAD

**Issue by inglesp** [PyconUK/planning2015#21]

**Comment by ntoll** [comment]
This,

https://docs.google.com/spreadsheets/d/1VOJx395vQOlD9TXuIY9GJzaMaVsZpzst2UqPeGbltaU/edit?usp=sharing

is a revised copy of the spreadsheet I sent over to Sal at Bank of
America. I created rows 2, 3, 4 and 7. One of the Django Girls added
line items 5 and 6.

The general strategy is that we ask for the moon on a stick, they
suggest something less but still relatively generous (which is why
items 5 and 6 were added by DG).

Sal has explained that each item will also come out of separate
sponsorship "pots" - for example there is a specific LGBT pot that
could be used to support TransCode activity at PyconUK.

I'm going to ping Sal today to find out what progress (if any) has
been made in the past 4 weeks.
